# Use root/password as user/password credentials

version: "3.1"

services:
  # Database
  mongoDB:
    image: mongo
    container_name: mongodb_container
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
